### ISSUE TITLE
In collection page when we are clicking on the option then the loading bar is coming very big.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---Junxing-Speed-Work---20-April-2022#1]
**The url:** 
https://www.snowverb.com/collections/new-season-ski-snowboard-jacket-pants-snowsuit-for-beginner-new-arrival

**Actual result:**
In collection page when we are clicking on the option then the loading bar is coming very big.
![image](https://user-images.githubusercontent.com/102131636/164158138-08550a24-f7b5-4bcd-be50-47eac66214ca.png)
The video issue: https://www.awesomescreenshot.com/video/8489457?key=722c5a5a6370b2461c41b12b01892d54

**Expected result:** 
As compared with the live site the loading bar is coming small.

**Comment by devRitikTamrakar** [comment]
issues are solved

**Comment by devabulabbas** [comment]
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
