### ISSUE TITLE
The button above the footer is not having the background color  as compared to live site.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---Junxing-Speed-Work---20-April-2022#3]
**Actual result**
The button above the footer is not having the background color  as compared to live site.
![image](https://user-images.githubusercontent.com/102131636/164189325-292a41a6-17be-44b1-88e1-b28c644746af.png)

**Expected result:**
The live is having the background color of the button.
![image](https://user-images.githubusercontent.com/102131636/164189477-96495fa0-f190-4cc1-8af9-eebd77f266c5.png)

**Comment by devabulabbas** [comment]
@devRitikTamrakar @sudhanshu0603 
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
